#!/bin/sh -e

if [ $# -lt 2 ]; then
	green "Usage: lesys batch ${BLUE}<group> <playbook> [<args>]"
	exit 1
fi

# Check group is not "none"
if [ "$1" = "none" ]; then
	red "Cannot batch a playbook on none"
	exit 1
fi

# Check group exists
N="$(query ".groups.$1 | length")"
if [ "$N" -eq 0 ]; then
	red "Group ${BLUE}$1${RED} does not exist"
	exit 1
fi

green "Running ${BLUE}$2${GREEN} on $N server" -n
if [ "$N" -eq 1 ]; then
	echo
else
	green "s"
fi

# Go through all systems in the group
for server in $(query ".groups.$1[]"); do
	blue "$server " -n
	"$DIR/commands/run" "$server" "$2" ${@: 3} ||
		(red "Batch failed with ${BLUE}$server";
		 exit 1)
done
