#!/bin/sh -e

if [ $# -ne 1 ]; then
	green "Usage: lesys info ${BLUE}<system>"
	exit 1
fi

if [ "$(echo "$CONFIG" | jq ".systems.$1 | length")" -eq 0 ]; then
	red "Could not find system ${BLUE}$1"
	exit 1
fi

green "Host: " -n
blue "$(echo "$CONFIG" | jq -r ".systems.$1.host")"
green "Port: " -n
blue "$(echo "$CONFIG" | jq -r ".systems.$1.port")"
green "User: " -n
blue "$(echo "$CONFIG" | jq -r ".systems.$1.user")"

if [ "$(echo "$CONFIG" | jq -r ".systems.$1.groups | length")" -eq 0 ]; then
	green "System is in no groups"
else
	GROUPS="$(echo "$CONFIG" | jq -r ".systems.$1.groups[]")"
	green "Groups: ${BLUE}$GROUPS"
fi
