#!/bin/sh -e

INCLUDE="os"

# $_PASS is given by Le Sysadmin
# The only question is: how do we put it in?

function sudo_execute() {
	OS="$(os_execute)"
	case "$OS" in
		Linux)
			# sudo -S gives problems with executions for programs that read
			#   from stdin, and in case the authentication has been kept
			#   (no password required), so let's do it this way
			# Drop the pass
			TEMP="$(mktemp)"
			touch "$TEMP"
			chmod 700 "$TEMP"
			echo "#!/bin/sh -e" >> "$TEMP"
			echo "echo \"$_PASS\"" >> "$TEMP"

			SUDO_ASKPASS="$TEMP" sudo -A $@ 2>&1 && ret=0 || ret=$?

			shred "$TEMP" || :
			rm "$TEMP"
			return $ret
		;;
		OpenBSD)
			# Thanks to: https://github.com/Duncaen/OpenDoas/issues/21#issuecomment-854727152
			OUT="$(echo "spawn doas $@;
				expect \"password: \" { send -- \"$_PASS\r\"};
				expect eof" | expect)"

			fail="Authentication failed"
			if [ "${OUT#*$fail}" != "$OUT" ]; then
				echo "sudo: $fail"
				return 99
			fi

			echo "$OUT"
		;;
		*)
			echo "sudo: unsupported OS $OS"
			return $EXIT_INCOMPATIBLE
		;;
	esac
}

EXECUTE="sudo_execute"
